.gitignore
Gemfile
Gemfile.lock
spec/rails_helper.rb

Add Code Coverage

---

spec/controllers/application_controller_spec.rb
spec/factories/provider.rb
spec/fixtures/vcr_cassettes/application_controller/multiple_providers.yml

Tests harvest_all and dump_whole_index methods.

Create application controller spec

---

README.md

- Add missing steps
- Add explanations
- Use https Github URL
- Fix typos

Update README: local installation steps

---

lib/tasks/oai_to_foxml.xsl
lib/tasks/oaiqdc_to_foxml.xsl

Removes contributing institution from the contributor field in the UI.
Removes Relation from relation field in the UI.

Tweaks to field mapping in UI

---

lib/encodings/constants.rb

New language values added to the LANG_ABBR hash as seen here. Addresses Issue #80

New language values added to constants

---

lib/dpla_utils.rb
lib/tasks/dpla.rake
spec/lib/dpla_utils_spec.rb

Fixes #81
~~** Do Merge - Integrating feedback on #81**~~ edited

Adds tasks to generate report of items in the local repo not in the DPLA

---

app/assets/stylesheets/providers.css.scss
app/controllers/providers_controller.rb
app/helpers/providers_helper.rb
app/jobs/harvest_all_by_institution.rb
app/jobs/harvest_all_by_intermediate_provider.rb
app/models/provider.rb
app/views/providers/index.html.erb
config/routes.rb
db/migrate/20160609122158_add_last_harvested_to_providers.rb
db/schema.rb
lib/harvest_utils.rb
spec/controllers/providers_controller_spec.rb
spec/jobs/harvest_all_by_institution_spec.rb
spec/lib/harvest_utils_spec.rb
spec/models/provider_spec.rb

Revert "Feature/dplah 67 harvest all from intermediate provider"

---

app/assets/stylesheets/providers.css.scss
app/controllers/providers_controller.rb
app/helpers/providers_helper.rb
app/jobs/harvest_all_by_intermediate_provider.rb
app/models/provider.rb
app/views/providers/index.html.erb
config/routes.rb
db/migrate/20160609122158_add_last_harvested_to_providers.rb
db/schema.rb
lib/harvest_utils.rb
spec/controllers/providers_controller_spec.rb
spec/jobs/harvest_all_by_institution_spec.rb
spec/lib/harvest_utils_spec.rb
spec/models/provider_spec.rb

@kelynch Because I reverted some of the commits related to #67 and #72, I decided to start fresh, instead if trying to revert reverts. This branch cherry-picks changes from #102 and #103, so they are new commit hashes and not affected by the reverts. 
I've successfully tested several times by reseting the dev db to make sure the migration works as expected,  but really want some another set of hands to try this out.
If this works for you as well, we can close #108.

Re-add last harvested and harvest by intermediate provider

---

app/mailers/harvest_mailer.rb

Inserts default email address if seed does not define one.

Jobs do not fail if no email is specified in seed.

---

lib/harvest_utils.rb

Prevents URLS in rights staements from getting "Http'ed"

Don't globally normalize rights

---

config/routes.rb

Use devise differently

---

.gitignore
Gemfile
Gemfile.lock
app/controllers/catalog_controller.rb
config/application.rb
config/facets.yml.example
setup.sh

Configure available facets based on those defined in `config/facets.yml`.
Adds the config_for gem to make the  loading of config easier.
Re #137

Make facets configurable

---

lib/tasks/oaiqdc_to_foxml.xsl

Map dcterms:issued to dc:date

---

Procfile
app/models/oai_rec.rb
app/models/provider.rb
lib/harvest_utils.rb
lib/tasks/oai.rake
lib/thumbnail_utils.rb

@bibliotechy - Let's review the changes to lib/thumbnail_utils.rb

Islandora harvests

---

app/controllers/csv_controller.rb

Allows export of all records in  a result set.
Fixes #117

Loop through all results. 

---

app/controllers/providers_controller.rb
app/helpers/providers_helper.rb
app/models/concerns/filterable.rb
app/models/provider.rb
app/views/providers/index.html.erb
spec/views/providers/index.html.erb_spec.rb

Add Drop down selector for providers

---

lib/harvest_utils.rb

@bibliotechy : Let's talk about this one. It's more of a patch and more complex than I like.

Fix URI for Islandora items

---

public/robots.txt

Block the creepers and crawlers

---

lib/harvest_utils.rb
spec/factories/provider.rb
spec/lib/harvest_utils_spec.rb

Adds support for file prefixing assumptions baked into XSLT
Relates to #134

Fixes issues with Islandora records not ingesting.

---

lib/thumbnail_utils.rb

Handles case when no asset_url is generated

---

lib/tasks/jetty.rake

Easiest to understand if you view it  [ignoring whitespace changes](https://github.com/tulibraries/dplah/compare/no-require-jettywrapper?expand=1&w=1).

Don't load jettywrapper tasks in prod

---

Gemfile
Gemfile.lock
app/models/provider.rb

Harvest all seeds in one action

---

config/locales/oai_seed_logs.en.yml
lib/harvest_utils.rb

- Detects all forms of whitespace
- Provides better logging and exception handling for invalid PIDS and
missing quarntine directory.

Search for white space for invalid PIDs

---

app/models/oai_rec.rb
lib/harvest_utils.rb
lib/string_helpers.rb
lib/thumbnail_utils.rb

Fixes space embedded in thumbnail URL

---

app/models/oai_rec.rb
lib/harvest_utils.rb
lib/string_helpers.rb
lib/string_refinements.rb
lib/thumbnail_utils.rb

- Implement with Ruby refinement instead of extend.

Implement String#match? as refinement

---

app/models/provider.rb
db/schema.rb
db/seeds.rb
lib/thumbnail_utils.rb

Creates a reposiotry type for sci hi

Working tumbnails for scihi
